version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: inventaris_postgres
    restart: always
    environment:
      POSTGRES_DB: inventaris_db
      POSTGRES_USER: central_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: